version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app/
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    container_name: mongo
volumes:
  mongo: