version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app/
    depends_on:
      - archiver-mongo
    environment:
      MONGO_URL: mongodb://archiver-mongo:27017
  archiver-mongo:
    image: mongo:focal
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    container_name: archiver-mongo
volumes:
  mongo:
